name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Welcome and thank you for contributing your first issue!"
        pr-message: "Welcome and thank you for contributing to this project! Please remember to add comments and remove sensative information from your Presets!"
